# Generated by Django 4.1 on 2022-08-27 02:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=65)),
                ('description', models.CharField(max_length=165)),
                ('slug', models.SlugField(unique=True)),
                ('price', models.PositiveIntegerField()),
                ('mileage', models.IntegerField()),
                ('transmission', models.CharField(choices=[('Manual', 'Manual'), ('Automático', 'Automático')], max_length=65)),
                ('manufacture_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2100)])),
                ('fuel_type', models.CharField(choices=[('Diesel', 'Diesel'), ('Elétrico', 'Elétrico'), ('Etanol', 'Etanol'), ('Flex', 'Flex'), ('Gasolina', 'Gasolina'), ('GNV', 'GNV'), ('Híbrido', 'Híbrido')], max_length=65)),
                ('interior_color', models.CharField(max_length=65)),
                ('exterior_color', models.CharField(max_length=65)),
                ('engine', models.CharField(max_length=65)),
                ('is_published', models.BooleanField(default=False)),
                ('cover', models.ImageField(upload_to='vehicles/covers/%Y/%m/%d/')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.category')),
            ],
        ),
    ]
